// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDucdDQ0Q9s13FZmNboJ0CXjt4BE236zd0',
    appId: '1:681508618650:web:fb43b6f8972ce212e9ba23',
    messagingSenderId: '681508618650',
    projectId: 'assetmanagement-9d7e1',
    authDomain: 'assetmanagement-9d7e1.firebaseapp.com',
    storageBucket: 'assetmanagement-9d7e1.appspot.com',
    measurementId: 'G-ZQHEZ8M8E9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABykFxK_AgoRzI-Bvy9fgXq0UKFStZbEM',
    appId: '1:681508618650:android:f38f6f7e8ea508d7e9ba23',
    messagingSenderId: '681508618650',
    projectId: 'assetmanagement-9d7e1',
    storageBucket: 'assetmanagement-9d7e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRAdl4DRjKkFguSAWnB55qIv9DewLzbHg',
    appId: '1:681508618650:ios:3ce6dc4d381e2d23e9ba23',
    messagingSenderId: '681508618650',
    projectId: 'assetmanagement-9d7e1',
    storageBucket: 'assetmanagement-9d7e1.appspot.com',
    iosBundleId: 'com.example.assetManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRAdl4DRjKkFguSAWnB55qIv9DewLzbHg',
    appId: '1:681508618650:ios:3ce6dc4d381e2d23e9ba23',
    messagingSenderId: '681508618650',
    projectId: 'assetmanagement-9d7e1',
    storageBucket: 'assetmanagement-9d7e1.appspot.com',
    iosBundleId: 'com.example.assetManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDucdDQ0Q9s13FZmNboJ0CXjt4BE236zd0',
    appId: '1:681508618650:web:0e2b9bc7514f28f1e9ba23',
    messagingSenderId: '681508618650',
    projectId: 'assetmanagement-9d7e1',
    authDomain: 'assetmanagement-9d7e1.firebaseapp.com',
    storageBucket: 'assetmanagement-9d7e1.appspot.com',
    measurementId: 'G-4Y652V1VZH',
  );
}
